<?php

use Illuminate\Database\Seeder;

class master_module_seeder_template_v2 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
     /*
     Master Template of Seed Module Table
     exmple
     [
       'ModuleName'=>,
       'ModuleLink'=>,
       'ModuleParent'=>,
       'ModuleCount'=>,
       'ModuleUsers'=>,
       'ModuleAccessCode'=>,
     ],
     */

    public $masterTemplate = [
      [
        'id'=>1,
        'Status'=>1,
        'ModuleName'=>'Website',
        'ModuleLink'=>'dy',
        'ModuleParent'=>'0',
        'ModuleCount'=>'0',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>2,
        'Status'=>1,
        'ModuleName'=>'Basic Settings',
        'ModuleLink'=>'basic',
        'ModuleParent'=>'1',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>3,
        'Status'=>1,
        'ModuleName'=>'View',
        'ModuleLink'=>'batch',
        'ModuleParent'=>'2',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>4,
        'Status'=>1,
        'ModuleName'=>'Edit',
        'ModuleLink'=>'edit',
        'ModuleParent'=>'2',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>5,
        'Status'=>1,
        'ModuleName'=>'Organization Details',
        'ModuleLink'=>'od',
        'ModuleParent'=>'1',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>6,
        'Status'=>1,
        'ModuleName'=>'View',
        'ModuleLink'=>'batch',
        'ModuleParent'=>'5',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>7,
        'Status'=>1,
        'ModuleName'=>'Edit',
        'ModuleLink'=>'edit',
        'ModuleParent'=>'5',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>8,
        'Status'=>1,
        'ModuleName'=>'Board of Directors',
        'ModuleLink'=>'bod',
        'ModuleParent'=>'1',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>9,
        'Status'=>1,
        'ModuleName'=>'Add',
        'ModuleLink'=>'add',
        'ModuleParent'=>'8',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>10,
        'Status'=>1,
        'ModuleName'=>'Edit',
        'ModuleLink'=>'edit',
        'ModuleParent'=>'8',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>11,
        'Status'=>1,
        'ModuleName'=>'View',
        'ModuleLink'=>'batch',
        'ModuleParent'=>'8',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>12,
        'Status'=>1,
        'ModuleName'=>'Structure of Board',
        'ModuleLink'=>'sob',
        'ModuleParent'=>'1',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>13,
        'Status'=>1,
        'ModuleName'=>'Add',
        'ModuleLink'=>'add',
        'ModuleParent'=>'12',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>14,
        'Status'=>1,
        'ModuleName'=>'Edit',
        'ModuleLink'=>'edit',
        'ModuleParent'=>'12',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>15,
        'Status'=>1,
        'ModuleName'=>'View',
        'ModuleLink'=>'batch',
        'ModuleParent'=>'12',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>16,
        'Status'=>1,
        'ModuleName'=>'News & Announcements',
        'ModuleLink'=>'nam',
        'ModuleParent'=>'0',
        'ModuleCount'=>'0',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>17,
        'Status'=>1,
        'ModuleName'=>'News',
        'ModuleLink'=>'news',
        'ModuleParent'=>'16',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>18,
        'Status'=>1,
        'ModuleName'=>'Add',
        'ModuleLink'=>'add',
        'ModuleParent'=>'17',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>19,
        'Status'=>1,
        'ModuleName'=>'Edit',
        'ModuleLink'=>'edit',
        'ModuleParent'=>'17',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>20,
        'Status'=>1,
        'ModuleName'=>'View',
        'ModuleLink'=>'batch',
        'ModuleParent'=>'17',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>21,
        'Status'=>1,
        'ModuleName'=>'Announcements',
        'ModuleLink'=>'announcements',
        'ModuleParent'=>'16',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>22,
        'Status'=>1,
        'ModuleName'=>'Add',
        'ModuleLink'=>'add',
        'ModuleParent'=>'21',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>23,
        'Status'=>1,
        'ModuleName'=>'Edit',
        'ModuleLink'=>'edit',
        'ModuleParent'=>'21',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>24,
        'Status'=>1,
        'ModuleName'=>'View',
        'ModuleLink'=>'batch',
        'ModuleParent'=>'21',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],

      [
        'id'=>25,
        'Status'=>1,
        'ModuleName'=>'Milestone & Objectives',
        'ModuleLink'=>'mom',
        'ModuleParent'=>'0',
        'ModuleCount'=>'0',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>26,
        'Status'=>1,
        'ModuleName'=>'Milestone',
        'ModuleLink'=>'milestone',
        'ModuleParent'=>'25',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>27,
        'Status'=>1,
        'ModuleName'=>'Add',
        'ModuleLink'=>'add',
        'ModuleParent'=>'26',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>28,
        'Status'=>1,
        'ModuleName'=>'Edit',
        'ModuleLink'=>'edit',
        'ModuleParent'=>'26',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>29,
        'Status'=>1,
        'ModuleName'=>'View',
        'ModuleLink'=>'batch',
        'ModuleParent'=>'26',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>30,
        'Status'=>1,
        'ModuleName'=>'Objectives',
        'ModuleLink'=>'objectives',
        'ModuleParent'=>'25',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>31,
        'Status'=>1,
        'ModuleName'=>'Add',
        'ModuleLink'=>'add',
        'ModuleParent'=>'30',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>32,
        'Status'=>1,
        'ModuleName'=>'Edit',
        'ModuleLink'=>'edit',
        'ModuleParent'=>'30',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>33,
        'Status'=>1,
        'ModuleName'=>'View',
        'ModuleLink'=>'batch',
        'ModuleParent'=>'30',
        'ModuleCount'=>'2',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>34,
        'Status'=>1,
        'ModuleName'=>'Events',
        'ModuleLink'=>'em',
        'ModuleParent'=>'0',
        'ModuleCount'=>'0',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>35,
        'Status'=>1,
        'ModuleName'=>'Event Management',
        'ModuleLink'=>'em',
        'ModuleParent'=>'34',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>36,
        'Status'=>1,
        'ModuleName'=>'Add',
        'ModuleLink'=>'add',
        'ModuleParent'=>'35',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>37,
        'Status'=>1,
        'ModuleName'=>'Edit',
        'ModuleLink'=>'edit',
        'ModuleParent'=>'35',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>38,
        'Status'=>1,
        'ModuleName'=>'View',
        'ModuleLink'=>'batch',
        'ModuleParent'=>'35',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>39,
        'Status'=>1,
        'ModuleName'=>'Send Invitation',
        'ModuleLink'=>'send',
        'ModuleParent'=>'34',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>36,
        'Status'=>1,
        'ModuleName'=>'by Email',
        'ModuleLink'=>'byemail',
        'ModuleParent'=>'39',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],
      [
        'id'=>37,
        'Status'=>1,
        'ModuleName'=>'by SMS',
        'ModuleLink'=>'bysms',
        'ModuleParent'=>'39',
        'ModuleCount'=>'1',
        'ModuleAccessCode'=>'10',
      ],

    ];


    public function run()
    {
      $uc= new \BModel\User ();
      $uc=$uc->pluck('UserCode')->toArray();
    
     
      foreach ($this->masterTemplate as  $key=>$value) {

        $mod=new \BModel\Module();
        $value["ModuleCode"]=$mod->newModCode();
        $value["ModuleUsers"]=$uc;
        $array2=$mod->feedMod($value);
        $mod->feed($array2);
        $mod->checkSave();
      }
    }



}
